project:
  type: website
  output-dir: docs

website:
  title: "Bayesian Book Club"
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - references.qmd
    
      
format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

editor: visual

