---
title: "Schedule"
bibliography: references.bib
csl: american-sociological-association.csl
nocite: |
 @huntington-klein_effect_2025, @mcelreath_statistical_2020, @johnson_bayes_2022
page-layout: full
---

SR = *Statistical Rethinking* by Richard McElreath

SR(K)[^1] = Solomon Kurz's [translation of McElreath's book](https://solomon.quarto.pub/sr2/).

[^1]: McElreath's R code is primarily in base R, and much of the Bayesian sampling in SR utilizes a neat but idiosyncratic package of his own design. Kurz's workbook provides code for all of McElreath's exercises using tidyverse & [brms](https://github.com/paul-buerkner/brms) syntax. We'll make much use of the brms package, which allows us to specify Bayesian models using the same kind of syntax that we're all familiar with via lm() or lme4(). /n This means that Kurz's text is best utilized as a companion piece to SR---particularly for the model-specification procedures in R---rather than a wholly separate piece. 

BR = *Bayes Rules* by Johnson, Ott, and Dogucu

+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| Week    | Meeting Day | Topic                                                    | Reading(s) and Lecture content                                                                                                              |
+=========+=============+==========================================================+=============================================================================================================================================+
| 1       | June 19th   | Introduction to Bayesian thinking                        | - Chapters 1 & 2 of SR                                                                                                                      |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - [Introduction to Bayesian Workflow](https://www.youtube.com/watch?v=ztbYkBPDOgU&list=PLDcUM9US4XdNOlqSyhe38US8mFgmqzI14) (video lecture)  |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - [Frequentist statistics, the Null Ritual, and *p*-values](https://stefanocoretta.github.io/qdal/ch-null-ritual.html)                      |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - Chapter 1 of BR                                                                                                                           |
+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| 2       | TBA         | Bayesian probabilities and 'sampling from the imaginary' | - Chapters 3 & 4 in SR                                                                                                                      |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - Chapters 3 & 4 in SR(K)                                                                                                                   |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - [The Garden of Forking Data](https://www.youtube.com/watch?v=pGVkCWlXnlg&list=PLDcUM9US4XdNOlqSyhe38US8mFgmqzI14&index=2) (video lecture) |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - [Geocentric Models](https://www.youtube.com/watch?v=JX_UyidsQNg&list=PLDcUM9US4XdNOlqSyhe38US8mFgmqzI14&index=3) (video lecture)          |
+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| 3       | TBA         | Some practical and empirical grounding                   | - @brauer_employers_2021                                                                                                                    |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - @Makowski2019                                                                                                                             |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - @stanton_evaluating_2021                                                                                                                  |
+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| 4       | TBA         | Bayesian regression & causal inference                   | - Chapter 5 & 6 of SR                                                                                                                       |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - Chapter 5 & 6 of SR(K)                                                                                                                    |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          | - Optional supplements:                                                                                                                     |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          |   - Chapters 6 & 7 of [*The Effect*](https://theeffectbook.net/ch-CausalDiagrams.html)                                                      |
|         |             |                                                          |                                                                                                                                             |
|         |             |                                                          |   - [Andrew Heiss on measurement and DAGs](https://www.youtube.com/watch?v=kJQuH3nssfI) (video lecture)                                     |
+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| 5       | TBA         |                                                          |                                                                                                                                             |
+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| 6       | TBA         |                                                          |                                                                                                                                             |
+---------+-------------+----------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
